### PR TITLE
Add wifi down to Troubleshooting Tips

### PR DESCRIPTION
**Pull request by kc0euw**
Add the "wifi down" tip for troubleshooting firmware installs that 
result in a "bad gateway" message.

### CODE REVIEW

**Comment by kc0euw** [comment]
We've usually represented it like this:
node:# sysupgrade -n /tmp/aredn-firmware-filename.bin
But I can remove the # if it seems confusing. I wanted some way to indicate it is being executed with root privileges, but everything on the node has root so it may not be needed.

**Comment by kc0euw** [comment]
Let me know if that's clearer.  THX, Joe.

**Comment by ae6xe** [comment]
My preference would be one of these options:
A) match the login prompt of a node:  "root@<node name>:~# wifi down"
B) only what the end user types:    "wifi down"
C) if we needed a user to 'cd <dir>', then show the path in the prompt, exactly what the user would see.

**Comment by kc0euw** [comment]
In this case it seems clearer to include only what the user types.  I committed that change.  Let me know what you think.

**Pull request merged**
