### PR TITLE
add hidden/exposed status info

### PR DESCRIPTION
**Pull request by ab7pa**
This PR now only includes the addition of the new LQM statuses.  All discussion of exposed nodes has been removed and can be included in a separate PR if required in the future.

### CODE REVIEW

**Review by ae6xe — CHANGES_REQUESTED** [review]
in the exposed-node image:  "D should be allowed to transmit, but it cannot".   Actually,  both A and D could transmit at the same time -- B and C would receive the respective signals with no collisions.    In a common use case, if B and D are tower sites, then if C transmits, it prevents  B and D from receiving a signal from all other stations of both B and D.     If both B and D are transmitting at the same time, then C is deaf with 2 colliding received signals -- not an issue unless the traffic is intended for C.   OFDM is not like FM, where a receiver will lock onto a stronger signal, rather the energy of both signals is added together, and the resultant signal can not be decoded.

**Review by ae6xe — COMMENTED** [review]
Propose to bring out the scenario of 2 tower sites.  Add a node 'E' hanging off tower site 'D'.   the image could have B and D elevated above, with A, C, and D down below not seeing each other.   C would see both tower sites.    The significance of both tower sites,  each see C as an exposed node -- is to be aware of this node connecting both sites.  Then the tower admins, can consider 2 channels, instead of sharing 1, not allowing node C to connect to both at the same time -- something to always avoid.

**Comment by ab7pa** [comment]
I'm attempting to keep this as simple as possible, so I've changed the diagram to show the standard definition of the exposed node issue.  If folks need to drill down into more detail, several relevant links are provided in the text.

**Comment by aanon4** [comment]
I think the wording tweak fix the exposed node description. I dont think we should introduce another node to explain things - its confusing enough trying to explain this stuff as it is.

**Comment by ab7pa** [comment]
I reverted the changes to the **Channel Planning** section.  We can put them into a separate PR at some point.  `This PR now contains only the addition of the new LQM status identifiers.`

**Comment by ae6xe** [comment]
The Channel Planning section would work to elaborate (provide training).     Real world examples will help to simplify and understand the significance of exposed nodes.   We have a common example to use -- 2 tower sites joined together with an exposed node and horrible performance.   LQM is identifying hidden, exposed, and direct RF nodes.  I agree, LQM doesn't need to be the training document -- but when/if the Channel Planning is updated, could be referenced from LQM.

**Review by ae6xe — COMMENTED** [review]
Looks good.

**Pull request merged**
