### PR TITLE
add text for disabling firmware safety checks

### PR DESCRIPTION
**Pull request by ab7pa**

### CODE REVIEW

**Review by ae6xe — COMMENTED** [review]
Suggest to add:  "This setting is only appropriate to be used in circumstances to down/upgrade and the firmware versions are different targets architectures.  For example downgrading from ath79 back to ar71xx older firmware may require this setting to 'ON'".

I think this is true... comment by @aanon4  to confirm?

**Comment by ab7pa** [comment]
Sure, we can add more to the explanation.  We already have a [section in the documentation that describes the process of downgrading between architectures](https://docs.arednmesh.org/en/latest/arednHow-toGuides/firmware_tips.html#tips-for-downgrading-firmware).  Maybe we could add this additional method for downgrading in that existing section?

**Comment by ab7pa** [comment]
Added an example in the Adv Config doc as well as one in the Firmware Tips section.

**Comment by aanon4** [comment]
Description looks good to me. The primary reason I added this was to allow the specific example given - people will (and testers are) installing incorrect firmware, like a non-XL firmware when they mean the XL version. Minor of course, so this lets them carefully fix the problem. There are other uses of course, but this was the driver to do this.

**Comment by ae6xe** [comment]
should it be considered a defect that someone can install the non-XL firmware to an XL device?    We are enabling to go back, but why was it enabled to go forward?   Wouldn't the root cause fix be to block installing the wrong firmware, then this feature is needed only due to the change in target architecture?   Are we avoiding future incidences that would need to use this feature?

**Comment by ab7pa** [comment]
> should it be considered a defect that someone can install the non-XL firmware to an XL device? We are enabling to go back, but why was it enabled to go forward? Wouldn't the root cause fix be to block installing the wrong firmware, then this feature is needed only due to the change in target architecture? Are we avoiding future incidences that would need to use this feature?

Shouldn't this be raised as an Issue in the aredn/aredn repository?

**Comment by aanon4** [comment]
The way firmware upgrades work is that the current running firmware decides if the new firmware is okay or not. So if you were running a nightly build of a non-XL you would not be able to upgrade to an -XL version without the override options described here. However .. release doesnt make any distinction about these things - it doesnt care or understand if it's an XL or non-XL device (as far as the upgrade system is concerned), so you can't stop people doing the wrong thing. All we can do is stop them doing it again and provide a mechanism to help them if they make the release->nightly(next release) update incorrectly.

**Comment by ab7pa** [comment]
@ae6xe Joe, @aanon4 Tim confirmed that the description in this PR is accurate.  Is there anything else remaining before merging?  THX

**Review by ae6xe — APPROVED** [review]
Looks good.

**Pull request merged**
