### PR TITLE
Clarify firmware install steps

### PR DESCRIPTION
**Pull request by kc0euw**
Clarify firmware install process, especially the various IP addresses 
and subnets that may be required for different types of devices.

### CODE REVIEW

**Comment by kc0euw** [comment]
Randy, how about if I add more explanation...   
"...so you can give your computer a static IP on the 192.168.1.x network with a netmask of 255.255.255.0. For example, set your Ethernet adapter to a static IP address of 192.168.1.10. You can choose any number for the fourth octet, as long as it is not the same as the IP address of the node. Of course you must also avoid using 192.168.1.0 and 192.168.1.255, which are reserved addresses that identify the network itself and the broadcasts address for that network."

**Comment by kc0euw** [comment]
Joe,  how about something like this:
"Some devices may have DNS search paths configured and may require you to use the fully qualified domain name (FQDN) to resolve the mesh node's IP address."
   Also, the # was intended to indicate the root user's command prompt, but I can change it to ">" to make it consistent.

**Comment by ae6xe** [comment]
Yes, that works for me.

**Comment by kc0euw** [comment]
I just pushed the suggested changes, so they are included in this PR.  Thanks very much.

**Comment by wu2s** [comment]
Changes requested by Joe and Randy were included.

**Pull request merged**
