### PR TITLE
improve channel width description

### PR DESCRIPTION
**Pull request by ab7pa**
Adding more descriptive text for the _Channel Width_ setting.

### CODE REVIEW

**Review by ae6xe — COMMENTED** [review]
Re:  node may reduce power at higher link rates.   

While this behavior is stated in Ubiquiti specifications, I've never seen anything in ath9k or openwrt forums that suggests this occurs in the open source implementations.   I'd speculate that open source, and thus AREDN, does not have this behavior.  I've also not seen any information of what other vendor's do.

**Comment by ae6xe** [comment]
In the on node help, the 802.11n chips, we document the max allowed distance settings by channel width.    It would benefit to include here as well.

**Comment by ab7pa** [comment]
> In the on node help, the 802.11n chips, we document the max allowed distance settings by channel width. It would benefit to include here as well.

Yes, the same table was included in the online documentation at the same time it was added to the online help.

**Comment by ab7pa** [comment]
Removed line about power reduction, which originally came from the on node help file and may need to be removed there too.

**Review by ae6xe — COMMENTED** [review]
"For most AREDN devices".    The jury is still out if some devices can not meet the 10 and 5MHz channel widths.  I understand the latest news is recent success of AC devices linking in adhoc mode at these widths.   We are guessing if this will turn out to be "all" or "most" in the next release, so not sure what to do here.

**Comment by ab7pa** [comment]
Anything else still required for this documentation PR?

**Review by ae6xe — APPROVED** [review]
looks good.

**Pull request merged**
