### PR TITLE
clarify power limits for AREDN

### PR DESCRIPTION
**Pull request by ab7pa**
Clarify power limits for AREDN

### CODE REVIEW

**Review by dman776 — COMMENTED** [review]
should we add -3 and -4 on 2Ghz charts for non-US hams?

**Comment by ab7pa** [comment]
I did include those non-US channels on a previous version of the chart, but the feedback was that it was confusing some of the most vocal US hams.  I'm fine putting them back on now that we have warnings in the doc that they are responsible for complying with frequency and power level rules for their specific country's regulations.

**Comment by ae6xe** [comment]
Suggest to delay to let me review 1 issue.   While the reports back from our European users indicates that ch -3 and -4 are working, I have after the fact found a code issue, and wondering why it is even working at all.   I'd prefer to submit one more update in the code, before we more widely publish these channels, to avoid possible timebombs in this functionality.

**Comment by ab7pa** [comment]
Sounds good, @ae6xe Joe.  We can merge the existing diagrams that do **_not_** show channels -3 & -4.  Or we can wait on the whole PR.  I'm not in a hurry -- mainly wanted to clarify the recent power limits discussion in the forums.  THX

**Comment by wu2s** [comment]
Approved after discussion with Steve regarding power limits

**Pull request merged**
