### PR TITLE
add Network Discovery Tools section

### PR DESCRIPTION
**Pull request by ab7pa**
Add a new section for Network Discovery tools, including the meshmap programs and the spectral view/waterfall package.

### CODE REVIEW

**Review by dman776 — COMMENTED** [review]
We should add a disclaimer that these tools are not managed by the AREDN project at all.   They are supported by their authors at the noted urls.

**Comment by ab7pa** [comment]
I can do that, but really **none** of the programs mentioned in the entire *Applications and Services* section are supported by AREDN.  This section described various programs that people might want to consider running across their AREDN network, but none of them are supported by the AREDN team.

**Comment by ab7pa** [comment]
Added a disclaimer line in the initial overview doc, before describing _any_ of the potential programs that follow.  THX @dman776 .

**Review by dman776 — APPROVED** [review]
good additions.

**Pull request merged**
