### PR TITLE
Add x86_64 documentation

### PR DESCRIPTION
**Pull request by Marx1**
Added basic build guide for x86_64 image. This is my first time doing the markup, so some extra review may be needed. 

KG6MDW

### CODE REVIEW

**Comment by ab7pa** [comment]
Trevor, thanks VERY much for contributing this documentation.  One thing that I'm not sure if you were able to do -- did you test your PR using Sphinx as mentioned in the "contributing" section?

> AREDN® documentation is written using the [reStructuredText](https://docutils.sourceforge.io/docs/ref/rst/restructuredtext.html) markup language and your text is saved in “rst” files. Before committing your changes, be sure to test your rst files locally using [Sphinx](https://www.sphinx-doc.org/en/master/usage/quickstart.html) to ensure they will render correctly.

There are several things that need to be edited, and I'd be glad to do that.  I could merge your PR and then submit a second one with the edits -- some relate to markup quirks and some are copy edits (grammatical, missing word, etc).  Let me know if you have a preference.  THX

**Comment by Marx1** [comment]
I didn't see the contributing section; I did verify it on a reStructuedText validator I saw; but I didn't use Sphinx (I'm installing it on docker now)

Feel free to edit it - I had to adjust it a bit based on some findings from issue 1089 in the main repo.  I also know I have a different voice/way of talking as I'm a IT engineer; so I expect tweaks

**Comment by ab7pa** [comment]
Put this information into a separate How-To for advanced users. (see #337 )

**Comment by ab7pa** [comment]
Here is the completed doc for your review:  https://docs.arednmesh.org/en/latest/arednHow-toGuides/vm-install.html

**Comment by Marx1** [comment]
Looks great - a lot better wording/formatting that I had. Thanks for your assistance! I've been going down a rabbit hole with x86 stuff lately, and it's good to know there is at some basic documentation for people to get started from.

Trevor

**Pull request closed without merging**
