### PR TITLE
Revise Freq/Band Sections

### PR DESCRIPTION
**Pull request by ab7pa**
Revise freq/band sections to include updated 3.4ghz info.

### CODE REVIEW

**Comment by dman776** [comment]
@andre what do you think on this?

**Comment by K6AH** [comment]
Looks good to me.

**Review by ae6xe — COMMENTED** [review]
The 5.8ghz image says that the higher channels up to 185 are shared with unlicensed wifi.  This is not the case.  The recent 5GHz NPRM did allocate some to unlicensed (beyond 170), but not all the way to 185.     The primary is the DOT Vehicle Safety until the 5GHz NPRM takes some away.  We should start to document this Vehicle Safety primary.  There are locations in the country we (or another ham group) have interfered with already.

**Comment by ab7pa** [comment]
Good point, @ae6xe Joe.  I was also reviewing the [FCC doc](https://docs.fcc.gov/public/attachments/FCC-20-164A1.pdf) and agree.  I just pushed the updated diagrams.  Let me know...  thx

**Comment by ab7pa** [comment]
It looks to me like the FCC is making a small concession to the few DSRC "incumbent" implementations, but that they're moving everyone to C-V2X technology (section C) and they're restricting the Part 15 devices out of the upper 30 MHz.  

ITS-range

**Comment by ab7pa** [comment]
Effective date = "as of the effective date of this First Report and Order, we will allow immediate access for unlicensed indoor operations across the entire 5.850-5.895 GHz portion of the 5.9 GHz band."  The date on this order is November 20, 2020.

**Comment by ae6xe** [comment]
The "unlicensed" I believe means U-NNI-3 to put in the chart for the bottom 45MHz allocation.   Right now the image shows U-NNI-4 or ITS (now only top 30MHz allocation).

**Comment by ab7pa** [comment]
Interestingly, the FCC refers to that segment as the **U-NII-4** band which they are now combining with the existing **U-NII-3** range.  They don't seem to specify what the new unlicensed range will be called.
_"The combination of the U-NII-3 band with this new U-NII-4 band is greater than the sum of its parts. Whereas the upper portion of the U-NII-3 band can only support at most one 80-megahertz channel and the U-NII-4 band (in isolation) could only support a single 40-megahertz channel, together they can enable a single 160-megahertz channel for U- NII operations." (para 20)_

**Comment by ab7pa** [comment]
Do you think it's even necessary to identify the U-NII numbers and segments on our diagram?  Or can we just show that the entire 5.8ghz band is now shared with other users?

**Comment by ae6xe** [comment]
I don't believe that ITS can co-exist with U-NII-3 users.  it effectively removes usage for ITS from this space.  It means that every mobile device (cell phone, tablets, etc.) will start using this space traveling inside a car--and xmit at higher power than ITS.    U-NII-3 is also difficult to co-exist with part 97 and the predominate concern for hams to have awareness of.  To stick with the allocation, this 45MHz bandwidth is really labeled for both U-NNI-3 and U-NNI-4 according to the allocation.  Calling it only U-NNI-4 is a historically label.    (Minor, but I think we could remove U-NNI-4 because this space becomes unusable to them.)

**Comment by ae6xe** [comment]
In the past, we showed what was significant to know about.    We have not been showing ISM in 5GHz because we don't compete with microwave ovens and industrial toasters, it isn't significant that hams know about this allocation.  It is significant that hams know where wifi allocations are.    Note, we used to call all these bands the "ISM" bands, the historical allocation.

**Comment by ab7pa** [comment]
Cool.  How about this update to the diagrams: https://github.com/aredn/documentation/pull/105/commits/25ec35e23a341124ee7404b1193b34b33400153d

**Comment by ae6xe** [comment]
Looks good to me. Does anyone else want to contribute comments and this issue?

**Comment by K6AH** [comment]
I don't think hams will understand any of this.  I think it would be more
consistent to simply show these areas as shared channels.

**Comment by K6AH** [comment]
I'm fine with Steve's last proposal.

**Comment by ab7pa** [comment]
I'm good with whatever makes this diagram more understandable to the majority of hams.  I have a new set of diagrams that just say "Shared with other FCC authorized users" if you think that would be better.  Let me know and I can push them up to GitHub.

**Comment by ab7pa** [comment]
Let me know if these more generic "sharing" labels make things less confusing for the regular ham.  THX

**Comment by K6AH** [comment]
Steve, your latest diagram rev is fine with me.

**Comment by ab7pa** [comment]
U-NII labels or generic?

**Comment by ab7pa** [comment]
If we go with the generic labels, then we won't need to keep updating the graphics whenever the FCC changes their band plan over time.  Just a thought.

**Comment by ab7pa** [comment]
Nothing heard on "generic" sharing labels...  just posted U-NII labels with FCC NPRM footnotes.  Let me know if you think that's clearer for the average operator to understand.  THX

**Review by dman776 — APPROVED** [review]

**Pull request merged**
