### PR TITLE
Update Adv Config section

### PR DESCRIPTION
**Pull request by kc0euw**
Update the Advanced Config section with new AAM refresh setting and 
additional URL/path entries.

### CODE REVIEW

**Comment by kc0euw** [comment]
Added text specifying which node should have OLSR restarted.  Let me know if this clarifies it.  THX

**Comment by kc0euw** [comment]
I must be misinterpreting your [first comment](https://github.com/aredn/documentation/pull/59#pullrequestreview-392542557) above.  Sounds like OLSR restart always occurs on the local node, which was basically how this was worded before.

**Comment by kc0euw** [comment]
Does this (commit 3) make it clearer?  THX

**Comment by kc0euw** [comment]
Let's take a little time to think about it before making changes.  The basic idea is...

> The OLSR  process can be restarted when you want your node to rebuild its mesh routing table but you do not want to do a full reboot. There is a known intermittent issue that may occur when a node boots. If OLSR fails to propagate information or does not receive all the network hostnames, a one-time restart of OLSR should resolve the issue.

Do we need to give more details about why this occurs or what symptoms indicate that an OLSR restart might help?

**Comment by kc0euw** [comment]
Is there a **closed issue** link that we could refer people to for further information?

**Comment by ae6xe** [comment]
The problem is to define which node OLSR needs to be restarted.    If I see an IP address in mesh status on my node,    Restarting OLSR on my node does nothing.    If I see the IP address, e.g. 10.9.8.7,  then olsr needs restarted on the node 10.9.8.7.

**Comment by kc0euw** [comment]
How about something like this latest commit?  Does that help at all?

**Pull request merged**
