### PR TITLE
Replace Channel Width Example

### PR DESCRIPTION
**Pull request by ab7pa**
Replace the channel width example graphic in preparation for removing 
references to the 9cm band.

### CODE REVIEW

**Review by ae6xe — COMMENTED** [review]
ab7pa,  Is it easy to add in a label what channel # the examples are?  There can be confusion because 802.11n denotes the channel # at the center of the bandwidth consumed.  Other technologies, e.g. ATV channels, as I recall the frequency is the lower band edge.  New users may not pick this up and incorrectly determine where overlap may be occurring.

**Comment by ab7pa** [comment]
Let me know if this updated graphic is better.  Thanks very much, Joe AE6Xe!

**Review by ae6xe — APPROVED** [review]
looks good

**Comment by ab7pa** [comment]
Excellent!  Good clarification, too!

**Pull request merged**
