### PR TITLE
illustrate the exposed node problem

### PR DESCRIPTION
**Pull request by ab7pa**
Keeps the examples at a high level, but illustrates the hidden and exposed node issues.

### CODE REVIEW

**Review by Orv — APPROVED** [review]
Nice update.

**Review by ae6xe — COMMENTED** [review]
This is good.   Question is if we should elaborate more to help admins determine how small or big the throughput degradation is or could be.   In the real world examples I've seen, the 'E' node bypasses a back-bone link (multiple high-quality hops).   E can have marginal one-hop links to the 2 towers, and all the traffic between the nodes on both towers ends up going through E and low quality links -- performance can be horrible and no one knows why.    How do we plant the idea, from "it would be a good thing to avoid", to "expect horrible performance for everyone and never do".

**Comment by ab7pa** [comment]
If this PR is a useful basic illustration, then maybe in the future a more detailed set of examples or "admin helps" (?) could be created in the **_How-To_** section of the docs.  This **_Channel Planning_** section is already fairly large.

**Review by ae6xe — APPROVED** [review]
looks good.

**Pull request merged**
