### PR TITLE
fix wan wifi keysize text

### PR DESCRIPTION
**Pull request by ab7pa**

### CODE REVIEW

**Review by Orv — APPROVED** [review]
Looks good.

**Comment by ae6xe** [comment]
@ab7pa , doesn't the hex encoding still apply?  The openwrt wireless config option, "key", in use for this wifi client setup has hex in the description.    Not understanding why we'd remove this -- does it not work as documented by Openwrt?

**Comment by ab7pa** [comment]
To me the issue is how best to describe a feature to non-technical users in a way that is simple and clear.  The short sentence about hex encoding doesn't really add to users' understanding and could be confusing.  The OpenWRT configuration file /etc/config/wireless stores the key as a clear-text string, while our /etc/config.mesh/_setup file stores it as hex.  But users typically don't care how it is represented internally as long as it connects them to the Wifi AP they are using for WAN access.

**Comment by ae6xe** [comment]
The format of the key in the  _setup file is a simple encryption so that it is not a clear text format when we  persistently store a password -- from firmware upgrade to upgrade.   The password entered in AREDN setup by the end user could be in a "hex" format and is necessary if an AP we want to connect to actually has a password of non-printable characters -- it could.   This hex key, would then be further encrypted to store in _setup.

**Comment by ab7pa** [comment]
Restored the sentence about 64 char hex encoded keys.

**Review by ae6xe — APPROVED** [review]
Looks good.

**Pull request merged**
