### PR TITLE
Add Mesh Status local hosts color info

### PR DESCRIPTION
**Pull request by ab7pa**
Add display color info for DoNotPropagate nodes and Aliases on the Mesh 
Status page.

### CODE REVIEW

**Comment by ab7pa** [comment]
@ae6xe Joe, this PR has accumulated several small doc fixes.  Should be good to go, though.  Please review and let me know if any changes are required.  Many thanks!

**Review by ae6xe — COMMENTED** [review]
"git clone https://github.com/myCall/documentation"  

is there a commonly used syntax for 'insert your specific data here' notation that could be used?     With "myCall" it has no specific notation that indicates this.  Someone might interpret this literally.   What about "git clone https://github.ocm/<myCall>/documentation"    or use "[myCall]".   this is common when documenting command line when there are various options, some required and some not.

**Review by ae6xe — COMMENTED** [review]
in all the documentation where there is a git commit, option to reference the standards used by openwrt of how to structure the commit description to be more easily readable by others:   https://openwrt.org/submitting-patches
key idea is a commit description that concisely communicates to others what is in the commit.

**Comment by ab7pa** [comment]
Excellent ideas.  Added clarification to github username references, as well as resources for creating good commit messages.  THX

**Review by ae6xe — APPROVED** [review]
looks good.

**Pull request merged**
