### PR TITLE
Add Firmware Upgrade Tips

### PR DESCRIPTION
**Pull request by kc0euw**
Add a firmware upgrade tips How-To and clean up a couple of errors.

### CODE REVIEW

**Comment by kc0euw** [comment]
Would something like this be better:  _"Before starting the firmware upgrade, it may be necessary to stop or uninstall any packages you have manually installed (for example, MeshChat or IperfSpeed). The goal of this is to free up as much memory as possible before the upgrade."_

**Comment by ae6xe** [comment]
Could be specific and say "uninstall  Meshchat, hamchat, snmp, and tunnels to free up RAM memory".   Uninstalling any other package is unnecessary (unless I am forgetting a package that has something running all the time.)   iperf does not have a process running and consuming RAM all the time.

"memory" is generic given the 2 types of memory.  Use  "RAM memory" to be more specific.   freeing up "flash memory" is a non-factor and not necessary.

**Comment by ae6xe** [comment]
Actually, for tunnels, just make them 'inactive', don't have to uninstall the packages to free up RAM.

**Comment by kc0euw** [comment]
Second commit has the updated wording.  THX

**Pull request merged**
