### PR TITLE
add RTS Threshold to AdvConfig page

### PR DESCRIPTION
**Pull request by ab7pa**

### CODE REVIEW

**Review by ae6xe — COMMENTED** [review]
My understanding is that if RTS/CTS is active, the client will use it regardless when the packet size exceeds the threshold (this is the layer 3 "packet" size, and 802.11n/ac breaks this size into smaller "frames" to xmit over layer 2 wireless link).  

The statement "when hidden nodes are detected", I don't think is actuate.   RTS/CTS would be used even on  P2P link with no hidden nodes, where it wouldn't be needed.  

We might want more elaboration somewhere in the docs when/where to use RTS/CTS.   A tower node doesn't necessarily need to turn this on -- it sees all the nodes, no hidden generally.   But a tower node will respond to receiving a RTS, just wouldn't need to sent an RTS.

**Comment by ab7pa** [comment]
I'll be glad to word this in the clearest way possible, so I'm open to suggestion.
From what I can see in the code, though, it seems that the RTS value is only set when LQM detects hidden nodes.  From /usr/local/bin/mgr/lqm.lua:

Screenshot 2023-02-18 at 11 43 00 AM

**Comment by ae6xe** [comment]
When LQM is turned off, would setting a threshold value turn RTS on, and my comments apply?   Trying to recall, RTS/CTS is off by default, set the threshold in advanced config and it will always use RTS for packets over this threshold with LQM disabled?

**Comment by ae6xe** [comment]
how about, "The packet size in bytes triggering RTS/CTS when LQM detects hidden nodes."

**Review by ae6xe — APPROVED** [review]
looks good.

**Pull request merged**
