### PR TITLE
Reduce meshiness of Network Topology section

### PR DESCRIPTION
**Pull request by ab7pa**
Reduce the meshiness of the Network Topology section, while providing info about typical network topologies and their uses.

### CODE REVIEW

**Review by K6AH — COMMENTED** [review]
There is a spelleing problem in the following line: 
Endpoint links are used to connect destination nodes to the mesh network. Sometimes these links are **called** "last mile"...

**Comment by ab7pa** [comment]
Thanks @K6AH  --  fixed in the second commit above.

**Comment by Orv** [comment]
Line 59+: 

Different types of radio links may be needed to connect all of the mesh nodes that are required...

**Should be** 

Different types of radio links may be needed to connect all of the nodes that are required...

**Comment by ab7pa** [comment]
Done. THX @Orv

**Pull request merged**
